### ISSUE TITLE
Notificação para usuário

### ISSUE THREAD

**Issue by Junior-Shyko** [secultce/plugin-OpinionManagement#10]
### CONTEXTO

O plugin não tem uma forma de notificar os proponentes que as justificativas(_pareceres_) foi publicado e que o mesmo deve ir até sua inscrição para visualizar.

### CRITÉRIO DE ATENÇÃO

- [x] Notificação ao usuário pela plataforma

**Comment by ronnyjohnti** [comment]
Essa feature vai depender da implementação aberta na issue #5.
